package com.example.clockapp.WorldTime;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

public class CountryUtil {
    private  List<CountryModel> countryModelList = new ArrayList<>();

    public  class CountryModel {
        String name;
        String city;
        String timeGmt;

        public CountryModel(String name, String city, String timeGmt) {
            this.name = name;
            this.city = city;
            this.timeGmt = timeGmt;
        }

        public String getName() {
            return name;
        }

        public String getcity() {
            return city;
        }

        public String getTimeGmt() {
            return timeGmt;
        }

    }

    final  String[][] listCountry = {{"Afghanistan", "Asia/Kabul", "GMT+04:30"},
            {"Albania", "Europe/Tirane", "GMT+02:00"},
            {"Algeria", "Africa/Algiers", "GMT+01:00"},
            {"American Samoa", "Pacific/Pago_Pago", "GMT-11:00"},
            {"Andorra", "Europe/Andorra", "GMT+02:00"},
            {"Angola", "Africa/Luanda", "GMT+01:00"},
            {"Anguilla", "America/Anguilla", "GMT-04:00"},
            {"Antarctica", "Antarctica/Casey", "GMT+11:00"},
            {"Antarctica", "Antarctica/Davis", "GMT+07:00"},
            {"Antarctica", "Antarctica/DumontDUrville", "GMT+10:00"},
            {"Antarctica", "Antarctica/Mawson", "GMT+05:00"},
            {"Antarctica", "Antarctica/McMurdo", "GMT+12:00"},
            {"Antarctica", "Antarctica/Palmer", "GMT-03:00"},
            {"Antarctica", "Antarctica/Rothera", "GMT-03:00"},
            {"Antarctica", "Antarctica/Syowa", "GMT+03:00"},
            {"Antarctica", "Antarctica/Troll", "GMT+02:00"},
            {"Antarctica", "Antarctica/Vostok", "GMT+06:00"},
            {"Antigua and Barbuda", "America/Antigua", "GMT-04:00"},
            {"Argentina", "America/Argentina/Buenos_Aires", "GMT-03:00"},
            {"Argentina", "America/Argentina/Catamarca", "GMT-03:00"},
            {"Argentina", "America/Argentina/Cordoba", "GMT-03:00"},
            {"Argentina", "America/Argentina/Jujuy", "GMT-03:00"},
            {"Argentina", "America/Argentina/La_Rioja", "GMT-03:00"},
            {"Argentina", "America/Argentina/Mendoza", "GMT-03:00"},
            {"Argentina", "America/Argentina/Rio_Gallegos", "GMT-03:00"},
            {"Argentina", "America/Argentina/Salta", "GMT-03:00"},
            {"Argentina", "America/Argentina/San_Juan", "GMT-03:00"},
            {"Argentina", "America/Argentina/San_Luis", "GMT-03:00"},
            {"Argentina", "America/Argentina/Tucuman", "GMT-03:00"},
            {"Argentina", "America/Argentina/Ushuaia", "GMT-03:00"},
            {"Armenia", "Asia/Yerevan", "GMT+04:00"},
            {"Aruba", "America/Aruba", "GMT-04:00"},
            {"Australia", "Antarctica/Macquarie", "GMT+10:00"},
            {"Australia", "Australia/Adelaide", "GMT+09:30"},
            {"Australia", "Australia/Brisbane", "GMT+10:00"},
            {"Australia", "Australia/Broken_Hill", "GMT+09:30"},
            {"Australia", "Australia/Darwin", "GMT+09:30"},
            {"Australia", "Australia/Eucla", "GMT+08:45"},
            {"Australia", "Australia/Hobart", "GMT+10:00"},
            {"Australia", "Australia/Lindeman", "GMT+10:00"},
            {"Australia", "Australia/Lord_Howe", "GMT+10:30"},
            {"Australia", "Australia/Melbourne", "GMT+10:00"},
            {"Australia", "Australia/Perth", "GMT+08:00"},
            {"Australia", "Australia/Sydney", "GMT+10:00"},
            {"Austria", "Europe/Vienna", "GMT+02:00"},
            {"Azerbaijan", "Asia/Baku", "GMT+04:00"},
            {"Bahamas", "America/Nassau", "GMT-04:00"},
            {"Bahrain", "Asia/Bahrain", "GMT+03:00"},
            {"Bangladesh", "Asia/Dhaka", "GMT+06:00"},
            {"Barbados", "America/Barbados", "GMT-04:00"},
            {"Belarus", "Europe/Minsk", "GMT+03:00"},
            {"Belgium", "Europe/Brussels", "GMT+02:00"},
            {"Belize", "America/Belize", "GMT-06:00"},
            {"Benin", "Africa/Porto-Novo", "GMT+01:00"},
            {"Bermuda", "Atlantic/Bermuda", "GMT-03:00"},
            {"Bhutan", "Asia/Thimphu", "GMT+06:00"},
            {"Bolivia, Plurinational State of", "America/La_Paz", "GMT-04:00"},
            {"Bonaire, Sint Eustatius and Saba", "America/Kralendijk", "GMT-04:00"},
            {"Bosnia and Herzegovina", "Europe/Sarajevo", "GMT+02:00"},
            {"Botswana", "Africa/Gaborone", "GMT+02:00"},
            {"Brazil", "America/Araguaina", "GMT-03:00"},
            {"Brazil", "America/Bahia", "GMT-03:00"},
            {"Brazil", "America/Belem", "GMT-03:00"},
            {"Brazil", "America/Boa_Vista", "GMT-04:00"},
            {"Brazil", "America/Campo_Grande", "GMT-04:00"},
            {"Brazil", "America/Cuiaba", "GMT-04:00"},
            {"Brazil", "America/Eirunepe", "GMT-05:00"},
            {"Brazil", "America/Fortaleza", "GMT-03:00"},
            {"Brazil", "America/Maceio", "GMT-03:00"},
            {"Brazil", "America/Manaus", "GMT-04:00"},
            {"Brazil", "America/Noronha", "GMT-02:00"},
            {"Brazil", "America/Porto_Velho", "GMT-04:00"},
            {"Brazil", "America/Recife", "GMT-03:00"},
            {"Brazil", "America/Rio_Branco", "GMT-05:00"},
            {"Brazil", "America/Santarem", "GMT-03:00"},
            {"Brazil", "America/Sao_Paulo", "GMT-03:00"},
            {"British Indian Ocean Territory", "Indian/Chagos", "GMT+06:00"},
            {"Brunei Darussalam", "Asia/Brunei", "GMT+08:00"},
            {"Bulgaria", "Europe/Sofia", "GMT+03:00"},
            {"Burundi", "Africa/Bujumbura", "GMT+02:00"},
            {"Cambodia", "Asia/Phnom_Penh", "GMT+07:00"},
            {"Cameroon", "Africa/Douala", "GMT+01:00"},
            {"Canada", "America/Atikokan", "GMT-05:00"},
            {"Canada", "America/Blanc-Sablon", "GMT-04:00"},
            {"Canada", "America/Cambridge_Bay", "GMT-06:00"},
            {"Canada", "America/Creston", "GMT-07:00"},
            {"Canada", "America/Dawson", "GMT-07:00"},
            {"Canada", "America/Dawson_Creek", "GMT-07:00"},
            {"Canada", "America/Edmonton", "GMT-06:00"},
            {"Canada", "America/Fort_Nelson", "GMT-07:00"},
            {"Canada", "America/Glace_Bay", "GMT-03:00"},
            {"Canada", "America/Goose_Bay", "GMT-03:00"},
            {"Canada", "America/Halifax", "GMT-03:00"},
            {"Canada", "America/Inuvik", "GMT-06:00"},
            {"Canada", "America/Iqaluit", "GMT-04:00"},
            {"Canada", "America/Moncton", "GMT-03:00"},
            {"Canada", "America/Nipigon", "GMT-04:00"},
            {"Canada", "America/Pangnirtung", "GMT-04:00"},
            {"Canada", "America/Rainy_River", "GMT-05:00"},
            {"Canada", "America/Rankin_Inlet", "GMT-05:00"},
            {"Canada", "America/Regina", "GMT-06:00"},
            {"Canada", "America/Resolute", "GMT-05:00"},
            {"Canada", "America/St_Johns", "GMT-02:30"},
            {"Canada", "America/Swift_Current", "GMT-06:00"},
            {"Canada", "America/Thunder_Bay", "GMT-04:00"},
            {"Canada", "America/Toronto", "GMT-04:00"},
            {"Canada", "America/Vancouver", "GMT-07:00"},
            {"Canada", "America/Whitehorse", "GMT-07:00"},
            {"Canada", "America/Winnipeg", "GMT-05:00"},
            {"Canada", "America/Yellowknife", "GMT-06:00"},
            {"Cape Verde", "Atlantic/Cape_Verde", "GMT-01:00"},
            {"Cayman Islands", "America/Cayman", "GMT-05:00"},
            {"Central African Republic", "Africa/Bangui", "GMT+01:00"},
            {"Chad", "Africa/Ndjamena", "GMT+01:00"},
            {"Chile", "America/Punta_Arenas", "GMT-03:00"},
            {"Chile", "America/Santiago", "GMT-04:00"},
            {"Chile", "Pacific/Easter", "GMT-06:00"},
            {"China", "Asia/Shanghai", "GMT+08:00"},
            {"China", "Asia/Urumqi", "GMT+06:00"},
            {"Christmas Island", "Indian/Christmas", "GMT+07:00"},
            {"Cocos (Keeling) Islands", "Indian/Cocos", "GMT+06:30"},
            {"Colombia", "America/Bogota", "GMT-05:00"},
            {"Comoros", "Indian/Comoro", "GMT+03:00"},
            {"Congo", "Africa/Brazzaville", "GMT+01:00"},
            {"Congo, the Democratic Republic of the", "Africa/Kinshasa", "GMT+01:00"},
            {"Congo, the Democratic Republic of the", "Africa/Lubumbashi", "GMT+02:00"},
            {"Cook Islands", "Pacific/Rarotonga", "GMT-10:00"},
            {"Costa Rica", "America/Costa_Rica", "GMT-06:00"},
            {"Croatia", "Europe/Zagreb", "GMT+02:00"},
            {"Cuba", "America/Havana", "GMT-04:00"},
            {"Curaçao", "America/Curacao", "GMT-04:00"},
            {"Cyprus", "Asia/Famagusta", "GMT+03:00"},
            {"Cyprus", "Asia/Nicosia", "GMT+03:00"},
            {"Czech Republic", "Europe/Prague", "GMT+02:00"},
            {"Denmark", "Europe/Copenhagen", "GMT+02:00"},
            {"Djibouti", "Africa/Djibouti", "GMT+03:00"},
            {"Dominica", "America/Dominica", "GMT-04:00"},
            {"Dominican Republic", "America/Santo_Domingo", "GMT-04:00"},
            {"Ecuador", "America/Guayaquil", "GMT-05:00"},
            {"Ecuador", "Pacific/Galapagos", "GMT-06:00"},
            {"Egypt", "Africa/Cairo", "GMT+02:00"},
            {"El Salvador", "America/El_Salvador", "GMT-06:00"},
            {"Equatorial Guinea", "Africa/Malabo", "GMT+01:00"},
            {"Eritrea", "Africa/Asmara", "GMT+03:00"},
            {"Estonia", "Europe/Tallinn", "GMT+03:00"},
            {"Ethiopia", "Africa/Addis_Ababa", "GMT+03:00"},
            {"Falkland Islands (Malvinas)", "Atlantic/Stanley", "GMT-03:00"},
            {"Faroe Islands", "Atlantic/Faroe", "GMT+01:00"},
            {"Fiji", "Pacific/Fiji", "GMT+12:00"},
            {"Finland", "Europe/Helsinki", "GMT+03:00"},
            {"France", "Europe/Paris", "GMT+02:00"},
            {"French Guiana", "America/Cayenne", "GMT-03:00"},
            {"French Polynesia", "Pacific/Gambier", "GMT-09:00"},
            {"French Polynesia", "Pacific/Marquesas", "GMT-09:30"},
            {"French Polynesia", "Pacific/Tahiti", "GMT-10:00"},
            {"French Southern Territories", "Indian/Kerguelen", "GMT+05:00"},
            {"Gabon", "Africa/Libreville", "GMT+01:00"},
            {"Georgia", "Asia/Tbilisi", "GMT+04:00"},
            {"Germany", "Europe/Berlin", "GMT+02:00"},
            {"Germany", "Europe/Busingen", "GMT+02:00"},
            {"Gibraltar", "Europe/Gibraltar", "GMT+02:00"},
            {"Greece", "Europe/Athens", "GMT+03:00"},
            {"Greenland", "America/Nuuk", "GMT-02:00"},
            {"Greenland", "America/Thule", "GMT-03:00"},
            {"Grenada", "America/Grenada", "GMT-04:00"},
            {"Guadeloupe", "America/Guadeloupe", "GMT-04:00"},
            {"Guam", "Pacific/Guam", "GMT+10:00"},
            {"Guatemala", "America/Guatemala", "GMT-06:00"},
            {"Guernsey", "Europe/Guernsey", "GMT+01:00"},
            {"Guyana", "America/Guyana", "GMT-04:00"},
            {"Haiti", "America/Port-au-Prince", "GMT-04:00"},
            {"Holy See (Vatican City State)", "Europe/Vatican", "GMT+02:00"},
            {"Honduras", "America/Tegucigalpa", "GMT-06:00"},
            {"Hong Kong", "Asia/Hong_Kong", "GMT+08:00"},
            {"Hungary", "Europe/Budapest", "GMT+02:00"},
            {"India", "Asia/Kolkata", "GMT+05:30"},
            {"Indonesia", "Asia/Jakarta", "GMT+07:00"},
            {"Indonesia", "Asia/Jayapura", "GMT+09:00"},
            {"Indonesia", "Asia/Makassar", "GMT+08:00"},
            {"Indonesia", "Asia/Pontianak", "GMT+07:00"},
            {"Iran, Islamic Republic of", "Asia/Tehran", "GMT+04:30"},
            {"Iraq", "Asia/Baghdad", "GMT+03:00"},
            {"Ireland", "Europe/Dublin", "GMT+01:00"},
            {"Isle of Man", "Europe/Isle_of_Man", "GMT+01:00"},
            {"Israel", "Asia/Jerusalem", "GMT+03:00"},
            {"Italy", "Europe/Rome", "GMT+02:00"},
            {"Jamaica", "America/Jamaica", "GMT-05:00"},
            {"Japan", "Asia/Tokyo", "GMT+09:00"},
            {"Jersey", "Europe/Jersey", "GMT+01:00"},
            {"Jordan", "Asia/Amman", "GMT+03:00"},
            {"Kazakhstan", "Asia/Almaty", "GMT+06:00"},
            {"Kazakhstan", "Asia/Aqtau", "GMT+05:00"},
            {"Kazakhstan", "Asia/Aqtobe", "GMT+05:00"},
            {"Kazakhstan", "Asia/Atyrau", "GMT+05:00"},
            {"Kazakhstan", "Asia/Oral", "GMT+05:00"},
            {"Kazakhstan", "Asia/Qostanay", "GMT+06:00"},
            {"Kazakhstan", "Asia/Qyzylorda", "GMT+05:00"},
            {"Kenya", "Africa/Nairobi", "GMT+03:00"},
            {"Kiribati", "Pacific/Enderbury", "GMT+13:00"},
            {"Kiribati", "Pacific/Kiritimati", "GMT+14:00"},
            {"Kiribati", "Pacific/Tarawa", "GMT+12:00"},
            {"Korea, Democratic People's Republic of", "Asia/Pyongyang", "GMT+09:00"},
            {"Korea, Republic of", "Asia/Seoul", "GMT+09:00"},
            {"Kuwait", "Asia/Kuwait", "GMT+03:00"},
            {"Kyrgyzstan", "Asia/Bishkek", "GMT+06:00"},
            {"Lao People's Democratic Republic", "Asia/Vientiane", "GMT+07:00"},
            {"Latvia", "Europe/Riga", "GMT+03:00"},
            {"Lebanon", "Asia/Beirut", "GMT+03:00"},
            {"Lesotho", "Africa/Maseru", "GMT+02:00"},
            {"Libya", "Africa/Tripoli", "GMT+02:00"},
            {"Liechtenstein", "Europe/Vaduz", "GMT+02:00"},
            {"Lithuania", "Europe/Vilnius", "GMT+03:00"},
            {"Luxembourg", "Europe/Luxembourg", "GMT+02:00"},
            {"Macao", "Asia/Macau", "GMT+08:00"},
            {"Macedonia, the Former Yugoslav Republic of", "Europe/Skopje", "GMT+02:00"},
            {"Madagascar", "Indian/Antananarivo", "GMT+03:00"},
            {"Malawi", "Africa/Blantyre", "GMT+02:00"},
            {"Malaysia", "Asia/Kuala_Lumpur", "GMT+08:00"},
            {"Malaysia", "Asia/Kuching", "GMT+08:00"},
            {"Maldives", "Indian/Maldives", "GMT+05:00"},
            {"Malta", "Europe/Malta", "GMT+02:00"},
            {"Marshall Islands", "Pacific/Kwajalein", "GMT+12:00"},
            {"Marshall Islands", "Pacific/Majuro", "GMT+12:00"},
            {"Martinique", "America/Martinique", "GMT-04:00"},
            {"Mauritius", "Indian/Mauritius", "GMT+04:00"},
            {"Mayotte", "Indian/Mayotte", "GMT+03:00"},
            {"Mexico", "America/Bahia_Banderas", "GMT-05:00"},
            {"Mexico", "America/Cancun", "GMT-05:00"},
            {"Mexico", "America/Chihuahua", "GMT-06:00"},
            {"Mexico", "America/Hermosillo", "GMT-07:00"},
            {"Mexico", "America/Matamoros", "GMT-05:00"},
            {"Mexico", "America/Mazatlan", "GMT-06:00"},
            {"Mexico", "America/Merida", "GMT-05:00"},
            {"Mexico", "America/Mexico_City", "GMT-05:00"},
            {"Mexico", "America/Monterrey", "GMT-05:00"},
            {"Mexico", "America/Ojinaga", "GMT-06:00"},
            {"Mexico", "America/Tijuana", "GMT-07:00"},
            {"Micronesia, Federated States of", "Pacific/Chuuk", "GMT+10:00"},
            {"Micronesia, Federated States of", "Pacific/Kosrae", "GMT+11:00"},
            {"Micronesia, Federated States of", "Pacific/Pohnpei", "GMT+11:00"},
            {"Moldova, Republic of", "Europe/Chisinau", "GMT+03:00"},
            {"Monaco", "Europe/Monaco", "GMT+02:00"},
            {"Mongolia", "Asia/Choibalsan", "GMT+08:00"},
            {"Mongolia", "Asia/Hovd", "GMT+07:00"},
            {"Mongolia", "Asia/Ulaanbaatar", "GMT+08:00"},
            {"Montenegro", "Europe/Podgorica", "GMT+02:00"},
            {"Montserrat", "America/Montserrat", "GMT-04:00"},
            {"Mozambique", "Africa/Maputo", "GMT+02:00"},
            {"Myanmar", "Asia/Yangon", "GMT+06:30"},
            {"Namibia", "Africa/Windhoek", "GMT+02:00"},
            {"Nauru", "Pacific/Nauru", "GMT+12:00"},
            {"Nepal", "Asia/Kathmandu", "GMT+05:45"},
            {"Netherlands", "Europe/Amsterdam", "GMT+02:00"},
            {"New Caledonia", "Pacific/Noumea", "GMT+11:00"},
            {"New Zealand", "Pacific/Auckland", "GMT+12:00"},
            {"New Zealand", "Pacific/Chatham", "GMT+12:45"},
            {"Nicaragua", "America/Managua", "GMT-06:00"},
            {"Niger", "Africa/Niamey", "GMT+01:00"},
            {"Nigeria", "Africa/Lagos", "GMT+01:00"},
            {"Niue", "Pacific/Niue", "GMT-11:00"},
            {"Norfolk Island", "Pacific/Norfolk", "GMT+11:00"},
            {"Northern Mariana Islands", "Pacific/Saipan", "GMT+10:00"},
            {"Norway", "Europe/Oslo", "GMT+02:00"},
            {"Oman", "Asia/Muscat", "GMT+04:00"},
            {"Pakistan", "Asia/Karachi", "GMT+05:00"},
            {"Palau", "Pacific/Palau", "GMT+09:00"},
            {"Palestine, State of", "Asia/Gaza", "GMT+03:00"},
            {"Palestine, State of", "Asia/Hebron", "GMT+03:00"},
            {"Panama", "America/Panama", "GMT-05:00"},
            {"Papua New Guinea", "Pacific/Bougainville", "GMT+11:00"},
            {"Papua New Guinea", "Pacific/Port_Moresby", "GMT+10:00"},
            {"Paraguay", "America/Asuncion", "GMT-04:00"},
            {"Peru", "America/Lima", "GMT-05:00"},
            {"Philippines", "Asia/Manila", "GMT+08:00"},
            {"Pitcairn", "Pacific/Pitcairn", "GMT-08:00"},
            {"Poland", "Europe/Warsaw", "GMT+02:00"},
            {"Portugal", "Atlantic/Madeira", "GMT+01:00"},
            {"Portugal", "Europe/Lisbon", "GMT+01:00"},
            {"Puerto Rico", "America/Puerto_Rico", "GMT-04:00"},
            {"Qatar", "Asia/Qatar", "GMT+03:00"},
            {"Romania", "Europe/Bucharest", "GMT+03:00"},
            {"Russian Federation", "Asia/Anadyr", "GMT+12:00"},
            {"Russian Federation", "Asia/Barnaul", "GMT+07:00"},
            {"Russian Federation", "Asia/Chita", "GMT+09:00"},
            {"Russian Federation", "Asia/Irkutsk", "GMT+08:00"},
            {"Russian Federation", "Asia/Kamchatka", "GMT+12:00"},
            {"Russian Federation", "Asia/Khandyga", "GMT+09:00"},
            {"Russian Federation", "Asia/Krasnoyarsk", "GMT+07:00"},
            {"Russian Federation", "Asia/Magadan", "GMT+11:00"},
            {"Russian Federation", "Asia/Novokuznetsk", "GMT+07:00"},
            {"Russian Federation", "Asia/Novosibirsk", "GMT+07:00"},
            {"Russian Federation", "Asia/Omsk", "GMT+06:00"},
            {"Russian Federation", "Asia/Sakhalin", "GMT+11:00"},
            {"Russian Federation", "Asia/Srednekolymsk", "GMT+11:00"},
            {"Russian Federation", "Asia/Tomsk", "GMT+07:00"},
            {"Russian Federation", "Asia/Ust-Nera", "GMT+10:00"},
            {"Russian Federation", "Asia/Vladivostok", "GMT+10:00"},
            {"Russian Federation", "Asia/Yakutsk", "GMT+09:00"},
            {"Russian Federation", "Asia/Yekaterinburg", "GMT+05:00"},
            {"Russian Federation", "Europe/Astrakhan", "GMT+04:00"},
            {"Russian Federation", "Europe/Kaliningrad", "GMT+02:00"},
            {"Russian Federation", "Europe/Kirov", "GMT+03:00"},
            {"Russian Federation", "Europe/Moscow", "GMT+03:00"},
            {"Russian Federation", "Europe/Samara", "GMT+04:00"},
            {"Russian Federation", "Europe/Saratov", "GMT+04:00"},
            {"Russian Federation", "Europe/Ulyanovsk", "GMT+04:00"},
            {"Russian Federation", "Europe/Volgograd", "GMT+03:00"},
            {"Rwanda", "Africa/Kigali", "GMT+02:00"},
            {"Réunion", "Indian/Reunion", "GMT+04:00"},
            {"Saint Barthélemy", "America/St_Barthelemy", "GMT-04:00"},
            {"Saint Kitts and Nevis", "America/St_Kitts", "GMT-04:00"},
            {"Saint Lucia", "America/St_Lucia", "GMT-04:00"},
            {"Saint Martin (French part)", "America/Marigot", "GMT-04:00"},
            {"Saint Pierre and Miquelon", "America/Miquelon", "GMT-02:00"},
            {"Saint Vincent and the Grenadines", "America/St_Vincent", "GMT-04:00"},
            {"Samoa", "Pacific/Apia", "GMT+13:00"},
            {"San Marino", "Europe/San_Marino", "GMT+02:00"},
            {"Saudi Arabia", "Asia/Riyadh", "GMT+03:00"},
            {"Serbia", "Europe/Belgrade", "GMT+02:00"},
            {"Seychelles", "Indian/Mahe", "GMT+04:00"},
            {"Singapore", "Asia/Singapore", "GMT+08:00"},
            {"Sint Maarten (Dutch part)", "America/Lower_Princes", "GMT-04:00"},
            {"Slovakia", "Europe/Bratislava", "GMT+02:00"},
            {"Slovenia", "Europe/Ljubljana", "GMT+02:00"},
            {"Solomon Islands", "Pacific/Guadalcanal", "GMT+11:00"},
            {"Somalia", "Africa/Mogadishu", "GMT+03:00"},
            {"South Africa", "Africa/Johannesburg", "GMT+02:00"},
            {"South Georgia and the South Sandwich Islands", "Atlantic/South_Georgia", "GMT-02:00"},
            {"South Sudan", "Africa/Juba", "GMT+02:00"},
            {"Spain", "Africa/Ceuta", "GMT+02:00"},
            {"Spain", "Atlantic/Canary", "GMT+01:00"},
            {"Spain", "Europe/Madrid", "GMT+02:00"},
            {"Sri Lanka", "Asia/Colombo", "GMT+05:30"},
            {"Sudan", "Africa/Khartoum", "GMT+02:00"},
            {"Suriname", "America/Paramaribo", "GMT-03:00"},
            {"Svalbard and Jan Mayen", "Arctic/Longyearbyen", "GMT+02:00"},
            {"Swaziland", "Africa/Mbabane", "GMT+02:00"},
            {"Sweden", "Europe/Stockholm", "GMT+02:00"},
            {"Switzerland", "Europe/Zurich", "GMT+02:00"},
            {"Syrian Arab Republic", "Asia/Damascus", "GMT+03:00"},
            {"Taiwan, Province of China", "Asia/Taipei", "GMT+08:00"},
            {"Tajikistan", "Asia/Dushanbe", "GMT+05:00"},
            {"Tanzania, United Republic of", "Africa/Dar_es_Salaam", "GMT+03:00"},
            {"Thailand", "Asia/Bangkok", "GMT+07:00"},
            {"Timor-Leste", "Asia/Dili", "GMT+09:00"},
            {"Tokelau", "Pacific/Fakaofo", "GMT+13:00"},
            {"Tonga", "Pacific/Tongatapu", "GMT+13:00"},
            {"Trinidad and Tobago", "America/Port_of_Spain", "GMT-04:00"},
            {"Tunisia", "Africa/Tunis", "GMT+01:00"},
            {"Turkey", "Europe/Istanbul", "GMT+03:00"},
            {"Turkmenistan", "Asia/Ashgabat", "GMT+05:00"},
            {"Turks and Caicos Islands", "America/Grand_Turk", "GMT-04:00"},
            {"Tuvalu", "Pacific/Funafuti", "GMT+12:00"},
            {"Uganda", "Africa/Kampala", "GMT+03:00"},
            {"Ukraine", "Europe/Kiev", "GMT+03:00"},
            {"Ukraine", "Europe/Simferopol", "GMT+03:00"},
            {"Ukraine", "Europe/Uzhgorod", "GMT+03:00"},
            {"Ukraine", "Europe/Zaporozhye", "GMT+03:00"},
            {"United Arab Emirates", "Asia/Dubai", "GMT+04:00"},
            {"United Kingdom", "Europe/London", "GMT+01:00"},
            {"United States", "America/Adak", "GMT-09:00"},
            {"United States", "America/Anchorage", "GMT-08:00"},
            {"United States", "America/Boise", "GMT-06:00"},
            {"United States", "America/Chicago", "GMT-05:00"},
            {"United States", "America/Denver", "GMT-06:00"},
            {"United States", "America/Detroit", "GMT-04:00"},
            {"United States", "America/Indiana/Indianapolis", "GMT-04:00"},
            {"United States", "America/Indiana/Knox", "GMT-05:00"},
            {"United States", "America/Indiana/Marengo", "GMT-04:00"},
            {"United States", "America/Indiana/Petersburg", "GMT-04:00"},
            {"United States", "America/Indiana/Tell_City", "GMT-05:00"},
            {"United States", "America/Indiana/Vevay", "GMT-04:00"},
            {"United States", "America/Indiana/Vincennes", "GMT-04:00"},
            {"United States", "America/Indiana/Winamac", "GMT-04:00"},
            {"United States", "America/Juneau", "GMT-08:00"},
            {"United States", "America/Kentucky/Louisville", "GMT-04:00"},
            {"United States", "America/Kentucky/Monticello", "GMT-04:00"},
            {"United States", "America/Los_Angeles", "GMT-07:00"},
            {"United States", "America/Menominee", "GMT-05:00"},
            {"United States", "America/Metlakatla", "GMT-08:00"},
            {"United States", "America/New_York", "GMT-04:00"},
            {"United States", "America/Nome", "GMT-08:00"},
            {"United States", "America/North_Dakota/Beulah", "GMT-05:00"},
            {"United States", "America/North_Dakota/Center", "GMT-05:00"},
            {"United States", "America/North_Dakota/New_Salem", "GMT-05:00"},
            {"United States", "America/Phoenix", "GMT-07:00"},
            {"United States", "America/Sitka", "GMT-08:00"},
            {"United States", "America/Yakutat", "GMT-08:00"},
            {"United States", "Pacific/Honolulu", "GMT-10:00"},
            {"United States Minor Outlying Islands", "Pacific/Midway", "GMT-11:00"},
            {"United States Minor Outlying Islands", "Pacific/Wake", "GMT+12:00"},
            {"Uruguay", "America/Montevideo", "GMT-03:00"},
            {"Uzbekistan", "Asia/Samarkand", "GMT+05:00"},
            {"Uzbekistan", "Asia/Tashkent", "GMT+05:00"},
            {"Vanuatu", "Pacific/Efate", "GMT+11:00"},
            {"Venezuela, Bolivarian Republic of", "America/Caracas", "GMT-04:00"},
            {"Viet Nam", "Asia/Ho_Chi_Minh", "GMT+07:00"},
            {"Virgin Islands, British", "America/Tortola", "GMT-04:00"},
            {"Virgin Islands, U.S.", "America/St_Thomas", "GMT-04:00"},
            {"Wallis and Futuna", "Pacific/Wallis", "GMT+12:00"},
            {"Yemen", "Asia/Aden", "GMT+03:00"},
            {"Zambia", "Africa/Lusaka", "GMT+02:00"},
            {"Zimbabwe", "Africa/Harare", "GMT+02:00"},
            {"Åland Islands", "Europe/Mariehamn", "GMT+03:00"}};

    public  List<CountryModel> getCountryList() {
        if (countryModelList.size() == 0) {
            int i;
            for (i = 0; i < listCountry.length; i++) {
                countryModelList.add(
                        new CountryModel(
                                listCountry[i][0],
                                listCountry[i][1],
                                listCountry[i][2]));
            }
        }
        return countryModelList;
    }

    public  List<CountryModel> searchByCityOrCountry(String city) {
        List<CountryModel> list = new ArrayList<>();
        if (city != "") {
            for (CountryModel model : getCountryList()) {
                if (model.getName().toLowerCase().contains(city.toLowerCase()) ||
                        model.getcity().toLowerCase().contains(city.toLowerCase())) {
                    list.add(model);
                }
            }
            return list;
        }else{
            return  getCountryList();
        }
    }
}
